Fix #1446: Reintroduce subscriptions, and slots
oceanprotocol/pdr-backend pull request #1466
Opened 2024-07-26 16:28 UTC by idiom-bytes

## Description
Fixes #1446 

## Commit message
- [x] Updated GQLDF to include all tables (minus contracts)
- [x] Updated all logic to work w/ latest subgraph updates
- [x] Fixed tests
- [x] Updated sample data and fixtures for new test coverage
- [x] Updated** all ETL tests to work w/ latest fixture

2024-07-29 08:24 UTC, calina-c commented on pdr_backend/accuracy/app.py
> +    return lambda item: int(item.get("seconds_per_epoch", 0)) == seconds_per_epoch
`return int(item.get("seconds_per_epoch", 0)) == seconds_per_epoch` is enough.

lambda is a way to define anonymous functions but this function is named ("filter_func"). Using a lambda as an alias to a named function is moot.

2024-07-29 08:30 UTC, calina-c commented on pdr_backend/lake/table.py
> +    for _, member in TableType.__members__.items():
I think you can iterate through values() instead of items()

2024-07-29 08:34 UTC, calina-c requested changes

2024-07-29 08:34 UTC, calina-c commented on pdr_backend/lake_info/overview.py
>          return violations
shouldn't the violation(s) be added to the list of violations?

2024-07-29 08:34 UTC, calina-c commented on setup.py
> +    "black==24.2.0",
please revert this change.

2024-07-31 19:44 UTC, idiom-bytes commented
moved all logic over to https://github.com/oceanprotocol/pdr-backend/pull/1489 in order to simplify review & merge

2024-07-31 19:44 UTC, closed without merging