[Fix #1485] PdrDashboard v0.4 - Feeds page metrics
oceanprotocol/pdr-backend pull request #1486
Opened 2024-07-31 10:54 UTC by calina-c

2024-08-02 10:51 UTC, KatunaNorbert commented on pdr_backend/pdr_dashboard/dash_components/view_elements.py
> +            return "Number of subscriptions to feeds"
Rename to: "Number of subscriptions purchased across all feeds"

2024-08-02 13:08 UTC, KatunaNorbert requested changes

2024-08-02 13:08 UTC, KatunaNorbert commented on pdr_backend/pdr_dashboard/dash_components/util.py
> +                SUM(payout) as total_revenue,
The revenue should be calculated from subscription sales, how much revenue the feeds has brought from subscription sells

2024-08-05 10:23 UTC, kdetry reviewed
I have some suggestions about the code

2024-08-05 10:23 UTC, kdetry commented on pdr_backend/pdr_dashboard/pages/feeds.py
> +                "display": "flex",
we can put Div styles to the CSS file. We can use the div ID

2024-08-06 07:53 UTC, KatunaNorbert approved these changes

2024-08-06 08:12 UTC, merged