Fix #1538: The Predictoor page modal
oceanprotocol/pdr-backend pull request #1540
Opened 2024-08-21 09:39 UTC by kdetry

Fixes #1538

2024-08-21 13:08 UTC, kdetry commented
I will seperate the APY_APR issue from this PR

2024-08-22 06:00 UTC, calina-c requested changes

2024-08-22 06:00 UTC, calina-c commented on pdr_backend/pdr_dashboard/util/db.py
> +        print("query--->", query)
please remove prints

2024-08-22 08:30 UTC, kdetry commented on pdr_backend/pdr_dashboard/pages/predictoors.py
> +    def get_predictoor_graphs_modal_header(self, selected_row):
I can agree with you

2024-08-22 12:12 UTC, calina-c commented on pdr_backend/pdr_dashboard/callbacks/callbacks_feeds.py
> +        Output("feeds_modal", "is_open"),
shouldn't this remain "modal"?

2024-08-22 12:15 UTC, calina-c reviewed
I thought we were going to reuse the same modal, but I see we still have different feed and predictoor modals.

I'm thinking simply add a common callback when selecting a row.
If it's selected from the feeds table, show the feeds results (charts).
If it's selected from the predictoors table, show the predictoors results (charts).

2024-08-22 13:38 UTC, calina-c commented on pdr_backend/pdr_dashboard/callbacks/callbacks_feeds.py
> +            get_graphs_modal_header(
ok, then to simplify, I think you can use just "feeds-modal"/"predictoors-modal" and selected row as the parameter to get_graphs_modal_header and get_graphs_modal_body. Assemble based on case, inside the function itself, to keep more code in helpers than in callbacks files.

2024-08-22 13:43 UTC, calina-c requested changes
added just a few minor nitpicks

2024-08-23 12:12 UTC, KatunaNorbert commented
Feedback:

UI
- add gap between the charts so the yAxis legend is not right next to the previous chart
- display empty charts by default while the data is loading and then updated the charts so that by default the modal in not compressed and only showing the title. This was at one point the behaviour inside the feeds modal as well, I'm not sure what happened that now is changed

Functional
- Profit chart: display as in the home page showing the cumulative profit over time

2024-08-27 13:35 UTC, KatunaNorbert approved these changes

2024-08-28 07:39 UTC, calina-c commented on pdr_backend/pdr_dashboard/dash_components/modal.py
> +            if selected_row:
let's switch up the ifs here.
treat the empty selected_row case first
then move onto the rest

2024-08-28 07:40 UTC, calina-c commented on pdr_backend/pdr_dashboard/util/helpers.py
> +    safe_trigger_ids=None,
I just remembered here that safe trigger ids completely depend on the id, I will adjust these.

2024-08-28 08:24 UTC, kdetry reviewed
I have tested the code manually and reviewed it, and it looks good to me

2024-08-28 08:24 UTC, kdetry commented on pdr_backend/pdr_dashboard/dash_components/plots.py
> +        total_profit += slot_profit
ty for this fix

2024-08-28 08:24 UTC, kdetry commented on pdr_backend/pdr_dashboard/dash_components/modal.py
> +class ModalContent:
I like the class approach here

2024-08-28 10:40 UTC, calina-c approved these changes

2024-08-28 10:53 UTC, merged