Fix #732 - Refactor currency classes to reduce duplication
oceanprotocol/pdr-backend pull request #733
Opened 2024-03-04 12:45 UTC by trizin

Fixes #732

Changes proposed in this PR:

- Refactor currency classes to reduce duplication
- Enforce same unit in comparisons
- Specify types in all comparisons.
- New tests

2024-03-05 14:05 UTC, trentmc commented
@calina-c I defer to you to review this, since you've been more deeply enmeshed in it

2024-03-06 12:08 UTC, calina-c requested changes

2024-03-06 12:08 UTC, calina-c commented on pdr_backend/publisher/test/test_publish_assets.py
> +    print(mock_publish_asset.call_args_list)
do not create print statements. Please use logging if needed.

2024-03-06 12:08 UTC, calina-c commented on pdr_backend/util/currency_types.py
> +        return f"{self.amount}"
I would keep the quantifier to differentiate that it is not a regular number, when printing. But I'm fine either way.

2024-03-06 12:08 UTC, calina-c commented on pdr_backend/util/currency_types.py
> +        if other == 0:
why do we need special handling for zeroes?

2024-03-06 15:33 UTC, calina-c commented on pdr_backend/util/currency_types.py
> +        super().__init__(amt_eth)
I would reverse the order of these statements. First validate, then call super

2024-03-07 14:31 UTC, merged