Fix #685 - [Do Not Merge] - DuckDB - E2E Integration
oceanprotocol/pdr-backend pull request #758
Opened 2024-03-06 19:06 UTC by idiom-bytes

Fixes #685 

Changes included in this PR:

**[Process 1 - Ingestion + Load]**
- [x] Update GQL local/save-to-disk to use csv https://github.com/oceanprotocol/pdr-backend/issues/681
- [x] Fetch + insert new records into db https://github.com/oceanprotocol/pdr-backend/issues/682

2024-04-11 06:29 UTC, calina-c requested changes
I reviewed the first part of the changes. I'll add the rest to a subsequent review.

2024-04-11 06:29 UTC, calina-c commented on pdr_backend/analytics/test/test_get_predictions_info.py
> +from pdr_backend.lake.test.conftest import _clean_up_persistent_data_store
it it's importable, it shouldn't start with an underscore. That is the convention for strictly module functions.

2024-04-11 06:29 UTC, calina-c commented on pdr_backend/lake/base_data_store.py
> +        if not hasattr(cls, "_instances"):
this looks like some kind of singleton, but I think it needs more context/comments. And spacing between blocks and before the return statement.

2024-04-11 06:29 UTC, calina-c commented on pdr_backend/lake/csv_data_store.py
> +        return folder_path
please add a line before return statements (multiple instances in this file)

2024-04-11 06:29 UTC, calina-c commented on pdr_backend/lake/csv_data_store.py
> +    def _fill_with_zero(self, number: int, length: int = 10) -> str:
this is not **filling**, it is **padding**. Please adjust the name of this function.
You can also use something MUCH more simple, e.g. zfill, rjust or number formatting with f:

https://stackoverflow.com/questions/339007/how-do-i-pad-a-string-with-zeros

2024-04-11 07:12 UTC, calina-c requested changes
2/2 done reviewing.

Looks like an awesome job! Most comments are style and readability-related suggestions. Please also remove print statements.

2024-04-11 07:12 UTC, calina-c commented on pdr_backend/lake/table_registry.py
> +    def register_table(self, table_name: str, table_args: Tuple[str, SchemaDict, PPSS]):
please add return types in this file

2024-04-11 07:12 UTC, calina-c commented on pdr_backend/lake/table_registry.py
> +        target_tables = [table for table in target_tables if table is not None]
or simply filter out None values https://www.geeksforgeeks.org/filter-in-python/

2024-04-11 07:12 UTC, calina-c commented on pdr_backend/lake/test/resources.py
> +    if table_name in table_names:
easier:
table_names = [table_name] if table_name else persistent_data_store.get_table_names()
for table in table_names:
             persistent_data_store.duckdb_conn.execute(f"DROP TABLE {table}")

2024-04-11 07:12 UTC, calina-c commented on pdr_backend/lake/test/test_plutil.py
> +    table_name = get_table_name("test", TableType.ETL)
suggest to add: get_table_name("test", "inexistentType")

2024-04-11 07:12 UTC, calina-c commented on pdr_backend/lake/test/test_table.py
> +def _clean_up_persistent_data_store(tmpdir, table_name):
this seems like a violation of DRY with the other function doing the exact same thing in lake/test_resources

2024-04-11 07:12 UTC, calina-c commented on setup.py
> +    "duckdb",
please constrain the duckdb version.

2024-04-12 08:11 UTC, KatunaNorbert commented
I'm running into the following error when running the do_etl() flow in the bronz table step
<img width="724" alt="Screenshot 2024-04-12 at 10 27 24" src="https://github.com/oceanprotocol/pdr-backend/assets/37236152/01c7cbe1-9434-4a46-a614-d526e86e52d8">

2024-04-15 08:59 UTC, KatunaNorbert commented
fixed the type issue from above by specifying the data frame schema

2024-06-07 23:02 UTC, idiom-bytes commented
As requested by @kdetry, please do not modify this PR any longer.

It's stable and we're working towards integrating it with main.

2024-06-25 14:08 UTC, idiom-bytes commented
We have completed this merging this, closing the PR.

2024-06-25 14:08 UTC, closed without merging