Fix #933 [Bug][Pdr Submitter Mgr] Predictions are submitted before <= 60s
oceanprotocol/pdr-backend pull request #935
Opened 2024-04-22 11:57 UTC by trizin

Fixes #933

Changes proposed in this PR:

- Calculate all the predictions first
- Submit the ones where epoch is still active
- New test for the `test_calc_stakes_across_feeds` function

2024-04-22 12:05 UTC, calina-c approved these changes
please wait for tests to pass before merging. Approved at the request of Roberto, he doesn't have github on his phone

2024-04-25 11:47 UTC, trentmc requested changes
1.

> `(predict if <= 60000 s left)`

Something's up. It should be 60 s. (Is it confusing ms vs s?)

Related: I don't see where it's waiting, to be in the proper time window. 4 of 5 minutes it should basically be waiting, and 1 of 5 minutes it should be submitting predictions. 

----

Let's optimize the line with a prediction summary:

Status quo: `INFO Predicted, up: 0.03903993518259732 eth, down: 0.06096006481740268 eth for feed: Feed: 5m binance ADA/USDT 0x2c69ed60f8d122bda55d5996484a290eaa2b289c and slot: 1714044000`

My suggestion: `INFO: Predicted feed binance ADA/USDT 5m 0x2c69, slot 1714044000: up = 0.039 OCEAN, down = 0.0610 OCEAN (39.0% up).

Specific changes: (a) 'OCEAN' not 'eth', (b) Feed name & slot first, (c) Reduced precision of numbers, (d) Reduced precision of feed address

2024-04-25 12:38 UTC, trentmc commented
> Updated logs with waiting:

Looks much better!

> progress dots seem to be messing up the logs a bit

I've found them acceptable. 
- Without them it feels dead. 
- And with more verbose logging than dots, it's hard to filter to see the important logs.
- So let's keep them as is

2024-04-26 10:40 UTC, trentmc approved these changes

2024-04-26 13:26 UTC, merged